name: Create INF

on: [push]

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/checkout@v3
        with:
          path: tf-modules
          repository: "cbx0n/tf-modules"
      - run: |
          terraform init \ 
          -backend-config "resource_group_name=${{secrets.resource_group_name}}" \ 
          -backend-config "storage_account_name=${{secrets.storage_account_name}}" \ 
          -backend-config "container_name=${{secrets.container_name}}" \ 
          -backend-config "key=${{secrets.key}}"
        working-directory: ./main