name: Create INF

on: [push]

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}  
  rg: ${{ secrets.resource_group_name }}
  str: ${{ secrets.storage_account_name }}
  cn: ${{ secrets.container_name }}
  key: ${{ secrets.key }}

permissions:
  id-token: write  
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/checkout@v3
        with:
          path: tf-modules
          repository: "cbx0n/tf-modules"
      - run: |
          terraform init -backend-config "resource_group_name=$rg" -backend-config "storage_account_name=$str" -backend-config "container_name=$cn" -backend-config "key=$key"
        working-directory: ./main
